{"name":"JT_DateDataflow","description":"Query written by Journey Team to create the date dimension table","version":"1.0","culture":"en-US","modifiedTime":"2021-01-04T22:33:47.4614813+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Date_Dim (Old)":{"queryId":"0e727f16-617c-4568-87f4-a9b062269ddb","queryName":"Date_Dim (Old)"},"Time_Dim":{"queryId":"3c0074d5-8023-4db7-a338-4bb97d9bb2b7","queryName":"Time_Dim","queryGroupId":"02a394db-c514-4acd-829b-a0946840d68a","loadEnabled":true},"Refresh Info":{"queryId":"f51b70ca-de8b-4a6d-88f9-01f9b6ba51b0","queryName":"Refresh Info","queryGroupId":"02a394db-c514-4acd-829b-a0946840d68a","loadEnabled":true},"Local Time Zone":{"queryId":"1e332bf5-756b-411b-8d88-e1454601a0d3","queryName":"Local Time Zone","queryGroupId":"02a394db-c514-4acd-829b-a0946840d68a"},"Last Refresh Local":{"queryId":"c64a7323-b857-4fae-8c35-73588fd9bba8","queryName":"Last Refresh Local","queryGroupId":"02a394db-c514-4acd-829b-a0946840d68a"},"Date_Dim":{"queryId":"f76e98cb-98e4-4c65-9b35-26232fd25dea","queryName":"Date_Dim","queryGroupId":"16c59665-03d8-41d7-b6fe-3da6417449cf","loadEnabled":true},"Start Date":{"queryId":"4358fb8a-fc1e-473d-aac4-f9058d569577","queryName":"Start Date","queryGroupId":"16c59665-03d8-41d7-b6fe-3da6417449cf"},"End Date":{"queryId":"e23c41e2-0753-44e5-8240-e5233156a567","queryName":"End Date","queryGroupId":"16c59665-03d8-41d7-b6fe-3da6417449cf"},"Years Back":{"queryId":"eca035c6-2a94-4142-a548-ed19fa36787a","queryName":"Years Back","queryGroupId":"16c59665-03d8-41d7-b6fe-3da6417449cf"},"Years Forward":{"queryId":"936fbd8b-f5fd-4eac-be5b-af7acc6a6d2c","queryName":"Years Forward","queryGroupId":"16c59665-03d8-41d7-b6fe-3da6417449cf"},"Fiscal Year Start Month":{"queryId":"1ec5bc07-7e06-4d48-855d-7c6936f61d83","queryName":"Fiscal Year Start Month","queryGroupId":"16c59665-03d8-41d7-b6fe-3da6417449cf"},"Dynamic Start Date":{"queryId":"d23d8479-90e5-459f-8b12-ee782a25175f","queryName":"Dynamic Start Date","queryGroupId":"16c59665-03d8-41d7-b6fe-3da6417449cf"},"Dynamic End Date":{"queryId":"8e731f5f-a9c6-4374-935f-713f3f726fa2","queryName":"Dynamic End Date","queryGroupId":"16c59665-03d8-41d7-b6fe-3da6417449cf"},"TOPN":{"queryId":"355c0537-16ae-45d3-a97a-9fe17fefc3b3","queryName":"TOPN","queryGroupId":"c1437975-acc3-420d-9534-0d1af5ee9e0e"}},"document":"section Section1;\r\nshared #\"Date_Dim (Old)\" = let\r\n  #\"*PARAMETERS*\" = 1,\r\n  // This parameter determines the first year of this date dimension. Dates will begin on the 1st of January of the year written.\r\n  FromYear = 2016,\r\n  // This parameter determines the last year of this date dimension. The final date of the table will be December 31st of the year written.\r\n  ToYear = Date.Year(DateTime.LocalNow()),\r\n  // Use this parameter to set the month number that is the start of your organization's fiscal/financial year. (Example: If your fiscal year starts July, 7 should be written here.)\r\n  StartofFiscalYear = 7,\r\n  // This parameter determines the day considered the first day of the week.\r\n  firstDayofWeek = Day.Monday,\r\n  // Clear depiction of the first day of your table.\r\n  FromDate = #date(FromYear,1,1),\r\n  // Clear depiction of the last day of your table.\r\n  ToDate = #date(ToYear,12,31),\r\n  #\"*DATE TABLE*\" = 1,\r\n  Source = List.Dates(\r\n    FromDate,\r\n    Duration.Days(ToDate-FromDate)+1,\r\n    #duration(1,0,0,0)\r\n    ),\r\n  #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r\n  #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\", {{\"Column1\", \"Date\"}}),\r\n  #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Date\", type date}}),\r\n  #\"Inserted Year\" = Table.AddColumn(#\"Changed Type\", \"Year\", each Date.Year([Date]), Int64.Type),\r\n  #\"Inserted Start of Year\" = Table.AddColumn(#\"Inserted Year\", \"Start of Year\", each Date.StartOfYear([Date]), type date),\r\n  #\"Inserted End of Year\" = Table.AddColumn(#\"Inserted Start of Year\", \"End of Year\", each Date.EndOfYear([Date]), type date),\r\n  #\"Inserted Month\" = Table.AddColumn(#\"Inserted End of Year\", \"Month Bridge\", each Date.Month([Date]), Int64.Type),\r\n  #\"Inserted Month Number\" = Table.AddColumn(#\"Inserted Month\", \"Month Number\", each Text.PadStart(Text.From([Month Bridge]),2,\"0\"), Int64.Type),\r\n  #\"Removed Month\" = Table.RemoveColumns(#\"Inserted Month Number\", {\"Month Bridge\"}),\r\n  #\"Inserted Start of Month\" = Table.AddColumn(#\"Removed Month\", \"Start of Month\", each Date.StartOfMonth([Date]), type date),\r\n  #\"Inserted End of Month\" = Table.AddColumn(#\"Inserted Start of Month\", \"End of Month\", each Date.EndOfMonth([Date]), type date),\r\n  #\"Inserted Days in Month\" = Table.AddColumn(#\"Inserted End of Month\", \"Days in Month\", each Date.DaysInMonth([Date]), Int64.Type),\r\n  #\"Inserted Day\" = Table.AddColumn(#\"Inserted Days in Month\", \"Day\", each Date.Day([Date]), Int64.Type),\r\n  #\"Inserted Day Name\" = Table.AddColumn(#\"Inserted Day\", \"Day Name\", each Date.DayOfWeekName([Date]), type text),\r\n  #\"Inserted Day of Week\" = Table.AddColumn(#\"Inserted Day Name\", \"Day of Week\", each Date.DayOfWeek([Date]), Int64.Type),\r\n  #\"Inserted Day of Year\" = Table.AddColumn(#\"Inserted Day of Week\", \"Day of Year\", each Date.DayOfYear([Date]), Int64.Type),\r\n  #\"Inserted Month Name\" = Table.AddColumn(#\"Inserted Day of Year\", \"Month Name\", each Date.MonthName([Date]), type text),\r\n  #\"Inserted Quarter\" = Table.AddColumn(#\"Inserted Month Name\", \"Quarter\", each Date.QuarterOfYear([Date]), Int64.Type),\r\n  #\"Inserted Start of Quarter\" = Table.AddColumn(#\"Inserted Quarter\", \"Start of Quarter\", each Date.StartOfQuarter([Date]), type date),\r\n  #\"Inserted End of Quarter\" = Table.AddColumn(#\"Inserted Start of Quarter\", \"End of Quarter\", each Date.EndOfQuarter([Date]), type date),\r\n  #\"Inserted Week of Year\" = Table.AddColumn(#\"Inserted End of Quarter\", \"Week of Year\", each Date.WeekOfYear([Date],firstDayofWeek), Int64.Type),\r\n  #\"Inserted Week of Month\" = Table.AddColumn(#\"Inserted Week of Year\", \"Week of Month\", each Date.WeekOfMonth([Date],firstDayofWeek), Int64.Type),\r\n  #\"Inserted Start of Week\" = Table.AddColumn(#\"Inserted Week of Month\", \"Start of Week\", each Date.StartOfWeek([Date],firstDayofWeek), type date),\r\n  #\"Inserted End of Week\" = Table.AddColumn(#\"Inserted Start of Week\", \"End of Week\", each Date.EndOfWeek([Date],firstDayofWeek), type date),\r\n  FiscalMonthBaseIndex = 13 - StartofFiscalYear,\r\n  adjustedFiscalMonthBaseIndex = if(FiscalMonthBaseIndex>=12 or FiscalMonthBaseIndex<0) then 0 else FiscalMonthBaseIndex,\r\n  #\"Added Custom\" = Table.AddColumn(#\"Inserted End of Week\", \"FiscalBaseDate\", each Date.AddMonths([Date],adjustedFiscalMonthBaseIndex)),\r\n  #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\", {{\"FiscalBaseDate\", type date}}),\r\n  #\"Inserted Year1\" = Table.AddColumn(#\"Changed Type1\", \"Year.1\", each Date.Year([FiscalBaseDate]), Int64.Type),\r\n  #\"Renamed Columns1\" = Table.RenameColumns(#\"Inserted Year1\", {{\"Year.1\", \"Fiscal Year\"}}),\r\n  #\"Inserted Quarter1\" = Table.AddColumn(#\"Renamed Columns1\", \"Quarter.1\", each Date.QuarterOfYear([FiscalBaseDate]), Int64.Type),\r\n  #\"Renamed Columns2\" = Table.RenameColumns(#\"Inserted Quarter1\", {{\"Quarter.1\", \"Fiscal Quarter\"}}),\r\n  #\"Inserted Fiscal Month\" = Table.AddColumn(#\"Renamed Columns2\", \"Fiscal Month Bridge\", each Date.Month([FiscalBaseDate]), Int64.Type),\r\n  #\"Inserted Fiscal Month Number\" = Table.AddColumn(#\"Inserted Fiscal Month\", \"Fiscal Month Number\", each Text.PadStart(Text.From([Fiscal Month Bridge]),2,\"0\"), Int64.Type),\r\n  #\"Removed Fiscal Month\" = Table.RemoveColumns(#\"Inserted Fiscal Month Number\", {\"Fiscal Month Bridge\"}),\r\n  #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Fiscal Month\", {\"FiscalBaseDate\"}),\r\n  // Is Past is a useful filter when working with To Date formulas in Power BI, although there are certainly many other reasons to keep this filter in your backpocket.\r\n  #\"Is Past\" = Table.AddColumn(#\"Removed Columns\", \"Is Past\", each if [Date] < DateTime.Date(DateTime.LocalNow()) then true else false, type text),\r\n  // Below are labels to help users identify slicers/filters/categories more clearly.\r\n  #\"Quarter Name\" = Table.AddColumn(#\"Is Past\", \"Quarter Name\", each Text.Combine({\"Q\", Text.From([Quarter], \"en-US\")}), type text),\r\n  #\"Day Name Shortened\" = Table.AddColumn(#\"Quarter Name\", \"Day Name Shortened\", each Text.Start([Day Name], 3), type text),\r\n  #\"Month Name Shortened\" = Table.AddColumn(#\"Day Name Shortened\", \"Month Name Shortened\", each Text.Start([Month Name], 3), type text),\r\n  #\"Month Year\" = Table.AddColumn(#\"Month Name Shortened\", \"Month Year\", each Text.Combine({[Month Name Shortened], \" \", Text.From([Year], \"en-US\")}), type text),\r\n  #\"Quarter Year\" = Table.AddColumn(#\"Month Year\", \"Quarter Year\", each Text.Combine({[Quarter Name], \" \", Text.From([Year], \"en-US\")}), type text),\r\n  // Below are group indexes used to streamline some calculations.\r\n  #\"==Group Indexes==\" = #\"Quarter Year\",\r\n  #\"Grouped Rows\" = Table.Group(#\"Quarter Year\", {\"Year\", \"Month Number\"}, {{\"Month Year Index Grouping\", each _, type table [Date=date, Year=number, Start of Year=date, End of Year=date, Month=number, Start of Month=date, End of Month=date, Days in Month=number, Day=number, Day Name=text, Day of Week=number, Day of Year=number, Month Name=text, Quarter=number, Start of Quarter=date, End of Quarter=date, Week of Year=number, Week of Month=number, Start of Week=date, End of Week=date, Fiscal Year=number, Fiscal Quarter=number, Fiscal Month=number, Year Month Sort=number, Year Quarter Sort=number, Year Quarter Month Sort=number, Is Past=logical, Quarter Name=text, Day Name Shortened=text, Month Name Shortened=text, Month Year=text, Quarter Year=text, Year Week Sort=text]}}),\r\n  #\"Removed Other Columns\" = Table.SelectColumns(#\"Grouped Rows\", {\"Month Year Index Grouping\"}),\r\n  #\"Added Index\" = Table.AddIndexColumn(#\"Removed Other Columns\", \"Month Year Index\", 1, 1),\r\n  #\"Expanded Month Year Index\" = Table.ExpandTableColumn(#\"Added Index\", \"Month Year Index Grouping\", {\"Date\", \"Year\", \"Start of Year\", \"End of Year\", \"Month Number\", \"Start of Month\", \"End of Month\", \"Days in Month\", \"Day\", \"Day Name\", \"Day of Week\", \"Day of Year\", \"Month Name\", \"Quarter\", \"Start of Quarter\", \"End of Quarter\", \"Week of Year\", \"Week of Month\", \"Start of Week\", \"End of Week\", \"Fiscal Year\", \"Fiscal Quarter\", \"Fiscal Month Number\", \"Year Month Sort\", \"Year Quarter Sort\", \"Year Quarter Month Sort\", \"Is Past\", \"Quarter Name\", \"Day Name Shortened\", \"Month Name Shortened\", \"Month Year\", \"Quarter Year\"}, {\"Date\", \"Year\", \"Start of Year\", \"End of Year\", \"Month Number\", \"Start of Month\", \"End of Month\", \"Days in Month\", \"Day\", \"Day Name\", \"Day of Week\", \"Day of Year\", \"Month Name\", \"Quarter\", \"Start of Quarter\", \"End of Quarter\", \"Week of Year\", \"Week of Month\", \"Start of Week\", \"End of Week\", \"Fiscal Year\", \"Fiscal Quarter\", \"Fiscal Month Number\", \"Year Month Sort\", \"Year Quarter Sort\", \"Year Quarter Month Sort\", \"Is Past\", \"Quarter Name\", \"Day Name Shortened\", \"Month Name Shortened\", \"Month Year\", \"Quarter Year\"}),\r\n  #\"Grouped Rows1\" = Table.Group(#\"Expanded Month Year Index\", {\"Year\", \"Quarter\"}, {{\"Quarter Year Index Grouping\", each _, type table [Date=date, Year=number, Start of Year=date, End of Year=date, Month=number, Start of Month=date, End of Month=date, Days in Month=number, Day=number, Day Name=text, Day of Week=number, Day of Year=number, Month Name=text, Quarter=number, Start of Quarter=date, End of Quarter=date, Week of Year=number, Week of Month=number, Start of Week=date, End of Week=date, Fiscal Year=number, Fiscal Quarter=number, Fiscal Month=number, Year Month Sort=number, Year Quarter Sort=number, Year Quarter Month Sort=number, Is Past=logical, Quarter Name=text, Day Name Shortened=text, Month Name Shortened=text, Month Year=text, Quarter Year=text, Month Year Index=number]}}),\r\n  #\"Removed Other Columns1\" = Table.SelectColumns(#\"Grouped Rows1\", {\"Quarter Year Index Grouping\"}),\r\n  #\"Added Index1\" = Table.AddIndexColumn(#\"Removed Other Columns1\", \"Quarter Year Index\", 1, 1),\r\n  #\"Expanded Quarter Year Index Grouping\" = Table.ExpandTableColumn(#\"Added Index1\", \"Quarter Year Index Grouping\", {\"Date\", \"Year\", \"Start of Year\", \"End of Year\", \"Month Number\", \"Start of Month\", \"End of Month\", \"Days in Month\", \"Day\", \"Day Name\", \"Day of Week\", \"Day of Year\", \"Month Name\", \"Quarter\", \"Start of Quarter\", \"End of Quarter\", \"Week of Year\", \"Week of Month\", \"Start of Week\", \"End of Week\", \"Fiscal Year\", \"Fiscal Quarter\", \"Fiscal Month Number\", \"Year Month Sort\", \"Year Quarter Sort\", \"Year Quarter Month Sort\", \"Is Past\", \"Quarter Name\", \"Day Name Shortened\", \"Month Name Shortened\", \"Month Year\", \"Quarter Year\", \"Month Year Index\"}, {\"Date\", \"Year\", \"Start of Year\", \"End of Year\", \"Month Number\", \"Start of Month\", \"End of Month\", \"Days in Month\", \"Day\", \"Day Name\", \"Day of Week\", \"Day of Year\", \"Month Name\", \"Quarter\", \"Start of Quarter\", \"End of Quarter\", \"Week of Year\", \"Week of Month\", \"Start of Week\", \"End of Week\", \"Fiscal Year\", \"Fiscal Quarter\", \"Fiscal Month Number\", \"Year Month Sort\", \"Year Quarter Sort\", \"Year Quarter Month Sort\", \"Is Past\", \"Quarter Name\", \"Day Name Shortened\", \"Month Name Shortened\", \"Month Year\", \"Quarter Year\", \"Month Year Index\"}),\r\n  #\"Inserted Merged Column\" = Table.AddColumn(#\"Expanded Quarter Year Index Grouping\", \"Year Week Sort\", each Text.Combine({Text.From([Year], \"en-US\"), \".\", Text.From([Week of Year], \"en-US\")}), Int64.Type),\r\n  #\"Grouped Rows2\" = Table.Group(#\"Inserted Merged Column\", {\"Year\", \"Week of Year\"}, {{\"Year Week Index Grouping\", each _, type table [Date=date, Year=number, Start of Year=date, End of Year=date, Month=number, Start of Month=date, End of Month=date, Days in Month=number, Day=number, Day Name=text, Day of Week=number, Day of Year=number, Month Name=text, Quarter=number, Start of Quarter=date, End of Quarter=date, Week of Year=number, Week of Month=number, Start of Week=date, End of Week=date, Fiscal Year=number, Fiscal Quarter=number, Fiscal Month=number, Year Month Sort=number, Year Quarter Sort=number, Year Quarter Month Sort=number, Is Past=logical, Quarter Name=text, Day Name Shortened=text, Month Name Shortened=text, Month Year=text, Quarter Year=text, Month Year Index=number, Quarter Year Index=number, Year Week Sort=text]}}),\r\n  #\"Removed Other Columns2\" = Table.SelectColumns(#\"Grouped Rows2\", {\"Year Week Index Grouping\"}),\r\n  #\"Added Index2\" = Table.AddIndexColumn(#\"Removed Other Columns2\", \"Year Week Index\", 1, 1),\r\n  #\"Expanded Year Week Index Grouping\" = Table.ExpandTableColumn(#\"Added Index2\", \"Year Week Index Grouping\", {\"Date\", \"Year\", \"Start of Year\", \"End of Year\", \"Month Number\", \"Start of Month\", \"End of Month\", \"Days in Month\", \"Day\", \"Day Name\", \"Day of Week\", \"Day of Year\", \"Month Name\", \"Quarter\", \"Start of Quarter\", \"End of Quarter\", \"Week of Year\", \"Week of Month\", \"Start of Week\", \"End of Week\", \"Fiscal Year\", \"Fiscal Quarter\", \"Fiscal Month Number\", \"Is Past\", \"Quarter Name\", \"Day Name Shortened\", \"Month Name Shortened\", \"Month Year\", \"Quarter Year\", \"Month Year Index\", \"Quarter Year Index\"}, {\"Date\", \"Year\", \"Start of Year\", \"End of Year\", \"Month Number\", \"Start of Month\", \"End of Month\", \"Days in Month\", \"Day\", \"Day Name\", \"Day of Week\", \"Day of Year\", \"Month Name\", \"Quarter\", \"Start of Quarter\", \"End of Quarter\", \"Week of Year\", \"Week of Month\", \"Start of Week\", \"End of Week\", \"Fiscal Year\", \"Fiscal Quarter\", \"Fiscal Month Number\", \"Is Past\", \"Quarter Name\", \"Day Name Shortened\", \"Month Name Shortened\", \"Month Year\", \"Quarter Year\", \"Month Year Index\", \"Quarter Year Index\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded Year Week Index Grouping\", {{\"Month Number\", type text}, {\"Fiscal Month Number\", type text}}),\r\n  #\"Duplicated column\" = Table.DuplicateColumn(#\"Changed column type\", \"Month Number\", \"Month\"),\r\n  #\"Duplicated column 1\" = Table.DuplicateColumn(#\"Duplicated column\", \"Fiscal Month Number\", \"Fiscal Month\"),\r\n  // Type is lost after grouping and expanding. Re-adding column types here.\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Duplicated column 1\", {{\"Date\", type text}, {\"Month\", Int64.Type}, {\"Fiscal Month\", Int64.Type}, {\"Year\", Int64.Type}, {\"Days in Month\", Int64.Type}, {\"Day\", Int64.Type}, {\"Day of Week\", Int64.Type}, {\"Day of Year\", Int64.Type}, {\"Quarter\", Int64.Type}, {\"Week of Year\", Int64.Type}, {\"Week of Month\", Int64.Type}, {\"Fiscal Year\", Int64.Type}, {\"Fiscal Quarter\", Int64.Type}, {\"Month Year Index\", Int64.Type}, {\"Quarter Year Index\", Int64.Type}, {\"Year Week Index\", Int64.Type}}),\r\n  // Sorting is lost after grouping and expanding. Re-sorting by date here to streamline development and to make the table more sensible.\r\n  #\"Re-sorted Rows by Date\" = Table.Sort(#\"Changed column type 1\", {{\"Date\", Order.Ascending}}),\r\n  // For some reason, some duplicates were found during an upload. Resolving that here by removing duplicates.\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Re-sorted Rows by Date\", {\"Date\"}),\r\n  #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed duplicates\", {{\"Date\", type date}})\r\nin\r\n  #\"Changed Type2\";\r\nshared Time_Dim = let\r\n  // This Time Dimension was sourced largely from the time dimensions freely provided by FourMoo and Radacad. Generous people are awesome people.\r\n  Source = List.Times(#time(0, 0, 0), 84600, #duration(0, 0, 0, 1)),\r\n  #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r\n  #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\", {{\"Column1\", \"Time\"}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Time\", type time}}),\r\n  #\"Start of Hour\" = Table.AddColumn(#\"Changed column type\", \"Start of Hour\", each Time.StartOfHour([Time]), type time),\r\n  #\"End of Hour\" = Table.AddColumn(#\"Start of Hour\", \"End of Hour\", each Time.EndOfHour([Time]), type time),\r\n  Hour = Table.AddColumn(#\"End of Hour\", \"Hour\", each Time.Hour([Time]), type number),\r\n  Minute = Table.AddColumn(Hour, \"Minute\", each Time.Minute([Time]), type number),\r\n  Second = Table.AddColumn(Minute, \"Second\", each Time.Second([Time]), type number),\r\n  #\"AM/PM\" = Table.AddColumn(Second, \"AM/PM\", each if [Hour] <= 11 then \"AM\" else \"PM\", type text),\r\n  #\"Hour Label\" = Table.AddColumn(#\"AM/PM\", \"Hour Label\", each \"0\" & Text.From([Hour], \"en-NZ\"), type text),\r\n  #\"Extracted Last Characters\" = Table.TransformColumns(#\"Hour Label\", {{\"Hour Label\", each Text.End(_, 2), type text}}),\r\n  #\"Minute Label\" = Table.AddColumn(#\"Extracted Last Characters\", \"Minute Label\", each \"0\" & Text.From([Minute], \"en-NZ\"), type text),\r\n  #\"Extracted Last Characters1\" = Table.TransformColumns(#\"Minute Label\", {{\"Minute Label\", each Text.End(_, 2), type text}}),\r\n  #\"Inserted Prefix2\" = Table.AddColumn(#\"Extracted Last Characters1\", \"Second Label\", each \"0\" & Text.From([Second], \"en-NZ\"), type text),\r\n  #\"Extracted Last Characters2\" = Table.TransformColumns(#\"Inserted Prefix2\", {{\"Second Label\", each Text.End(_, 2), type text}}),\r\n  #\"Hour Bin 12\" = Table.AddColumn(#\"Extracted Last Characters2\", \"Hour Bin 12\", each Number.Mod([Hour], 12), type number),\r\n  #\"Hour Bin 8\" = Table.AddColumn(#\"Hour Bin 12\", \"Hour Bin 8\", each Number.IntegerDivide([Hour], 8), Int64.Type),\r\n  #\"Hour Bin 6\" = Table.AddColumn(#\"Hour Bin 8\", \"Hour Bin 6\", each Number.IntegerDivide([Hour], 6), Int64.Type),\r\n  #\"Hour Bin 4\" = Table.AddColumn(#\"Hour Bin 6\", \"Hour Bin 4\", each Number.IntegerDivide([Hour], 4), Int64.Type),\r\n  #\"Hour Bin 3\" = Table.AddColumn(#\"Hour Bin 4\", \"Hour Bin 3\", each Number.IntegerDivide([Hour], 3), Int64.Type),\r\n  #\"Hour Bin 2\" = Table.AddColumn(#\"Hour Bin 3\", \"Hour Bin 2\", each Number.IntegerDivide([Hour], 2), Int64.Type),\r\n  #\"Minute Bin 30\" = Table.AddColumn(#\"Hour Bin 2\", \"Minute Bin 30\", each Number.IntegerDivide([Minute], 30), Int64.Type),\r\n  #\"Multiplied Column\" = Table.TransformColumns(#\"Minute Bin 30\", {{\"Minute Bin 30\", each _ * 30, type number}}),\r\n  #\"Minute Bin 15\" = Table.AddColumn(#\"Multiplied Column\", \"Minute Bin 15\", each Number.IntegerDivide([Minute], 15), Int64.Type),\r\n  #\"Multiplied Column1\" = Table.TransformColumns(#\"Minute Bin 15\", {{\"Minute Bin 15\", each _ * 15, type number}}),\r\n  #\"Minute Bin 10\" = Table.AddColumn(#\"Multiplied Column1\", \"Minute Bin 10\", each Number.IntegerDivide([Minute], 10), Int64.Type),\r\n  #\"Multiplied Column2\" = Table.TransformColumns(#\"Minute Bin 10\", {{\"Minute Bin 10\", each _ * 10, type number}})\r\nin\r\n  #\"Multiplied Column2\";\r\nshared #\"Refresh Info\" = let\r\n  Source = DateTime.From(DateTimeZone.FixedUtcNow()),\r\n  #\"Converted to table\" = #table(1, {{Source}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Converted to table\", {{\"Column1\", type datetime}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Changed column type\", {{\"Column1\", \"Last Refresh UTC\"}}),\r\n  #\"Added custom\" = Table.AddColumn(#\"Renamed columns\", \"Last Refresh Local\", each #\"Last Refresh Local\", type datetime),\r\n  #\"Added custom 1\" = Table.AddColumn(#\"Added custom\", \"Local Time Zone\", each #\"Local Time Zone\", type text)\r\nin\r\n  #\"Added custom 1\";\r\nshared #\"Local Time Zone\" = let\r\n  #\"Local Time Zone\" = \"America/Denver\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text, List = {\"Africa/Abidjan\", \"Africa/Accra\", \"Africa/Algiers\", \"Africa/Bissau\", \"Africa/Cairo\", \"Africa/Casablanca\", \"Africa/Ceuta\", \"Africa/El_Aaiun\", \"Africa/Johannesburg\", \"Africa/Juba\", \"Africa/Khartoum\", \"Africa/Lagos\", \"Africa/Maputo\", \"Africa/Monrovia\", \"Africa/Nairobi\", \"Africa/Ndjamena\", \"Africa/Sao_Tome\", \"Africa/Tripoli\", \"Africa/Tunis\", \"Africa/Windhoek\", \"America/Adak\", \"America/Anchorage\", \"America/Araguaina\", \"America/Argentina/Buenos_Aires\", \"America/Argentina/Catamarca\", \"America/Argentina/Cordoba\", \"America/Argentina/Jujuy\", \"America/Argentina/La_Rioja\", \"America/Argentina/Mendoza\", \"America/Argentina/Rio_Gallegos\", \"America/Argentina/Salta\", \"America/Argentina/San_Juan\", \"America/Argentina/San_Luis\", \"America/Argentina/Tucuman\", \"America/Argentina/Ushuaia\", \"America/Asuncion\", \"America/Atikokan\", \"America/Bahia\", \"America/Bahia_Banderas\", \"America/Barbados\", \"America/Belem\", \"America/Belize\", \"America/Blanc-Sablon\", \"America/Boa_Vista\", \"America/Bogota\", \"America/Boise\", \"America/Cambridge_Bay\", \"America/Campo_Grande\", \"America/Cancun\", \"America/Caracas\", \"America/Cayenne\", \"America/Chicago\", \"America/Chihuahua\", \"America/Costa_Rica\", \"America/Creston\", \"America/Cuiaba\", \"America/Curacao\", \"America/Danmarkshavn\", \"America/Dawson\", \"America/Dawson_Creek\", \"America/Denver\", \"America/Detroit\", \"America/Edmonton\", \"America/Eirunepe\", \"America/El_Salvador\", \"America/Fort_Nelson\", \"America/Fortaleza\", \"America/Glace_Bay\", \"America/Goose_Bay\", \"America/Grand_Turk\", \"America/Guatemala\", \"America/Guayaquil\", \"America/Guyana\", \"America/Halifax\", \"America/Havana\", \"America/Hermosillo\", \"America/Indiana/Indianapolis\", \"America/Indiana/Knox\", \"America/Indiana/Marengo\", \"America/Indiana/Petersburg\", \"America/Indiana/Tell_City\", \"America/Indiana/Vevay\", \"America/Indiana/Vincennes\", \"America/Indiana/Winamac\", \"America/Inuvik\", \"America/Iqaluit\", \"America/Jamaica\", \"America/Juneau\", \"America/Kentucky/Louisville\", \"America/Kentucky/Monticello\", \"America/La_Paz\", \"America/Lima\", \"America/Los_Angeles\", \"America/Maceio\", \"America/Managua\", \"America/Manaus\", \"America/Martinique\", \"America/Matamoros\", \"America/Mazatlan\", \"America/Menominee\", \"America/Merida\", \"America/Metlakatla\", \"America/Mexico_City\", \"America/Miquelon\", \"America/Moncton\", \"America/Monterrey\", \"America/Montevideo\", \"America/Nassau\", \"America/New_York\", \"America/Nipigon\", \"America/Nome\", \"America/Noronha\", \"America/North_Dakota/Beulah\", \"America/North_Dakota/Center\", \"America/North_Dakota/New_Salem\", \"America/Nuuk\", \"America/Ojinaga\", \"America/Panama\", \"America/Pangnirtung\", \"America/Paramaribo\", \"America/Phoenix\", \"America/Port-au-Prince\", \"America/Port_of_Spain\", \"America/Porto_Velho\", \"America/Puerto_Rico\", \"America/Punta_Arenas\", \"America/Rainy_River\", \"America/Rankin_Inlet\", \"America/Recife\", \"America/Regina\", \"America/Resolute\", \"America/Rio_Branco\", \"America/Santarem\", \"America/Santiago\", \"America/Santo_Domingo\", \"America/Sao_Paulo\", \"America/Scoresbysund\", \"America/Sitka\", \"America/St_Johns\", \"America/Swift_Current\", \"America/Tegucigalpa\", \"America/Thule\", \"America/Thunder_Bay\", \"America/Tijuana\", \"America/Toronto\", \"America/Vancouver\", \"America/Whitehorse\", \"America/Winnipeg\", \"America/Yakutat\", \"America/Yellowknife\", \"Antarctica/Casey\", \"Antarctica/Davis\", \"Antarctica/DumontDUrville\", \"Antarctica/Macquarie\", \"Antarctica/Mawson\", \"Antarctica/Palmer\", \"Antarctica/Rothera\", \"Antarctica/Syowa\", \"Antarctica/Troll\", \"Antarctica/Vostok\", \"Asia/Almaty\", \"Asia/Amman\", \"Asia/Anadyr\", \"Asia/Aqtau\", \"Asia/Aqtobe\", \"Asia/Ashgabat\", \"Asia/Atyrau\", \"Asia/Baghdad\", \"Asia/Baku\", \"Asia/Bangkok\", \"Asia/Barnaul\", \"Asia/Beirut\", \"Asia/Bishkek\", \"Asia/Brunei\", \"Asia/Chita\", \"Asia/Choibalsan\", \"Asia/Colombo\", \"Asia/Damascus\", \"Asia/Dhaka\", \"Asia/Dili\", \"Asia/Dubai\", \"Asia/Dushanbe\", \"Asia/Famagusta\", \"Asia/Gaza\", \"Asia/Hebron\", \"Asia/Ho_Chi_Minh\", \"Asia/Hong_Kong\", \"Asia/Hovd\", \"Asia/Irkutsk\", \"Asia/Jakarta\", \"Asia/Jayapura\", \"Asia/Jerusalem\", \"Asia/Kabul\", \"Asia/Kamchatka\", \"Asia/Karachi\", \"Asia/Kathmandu\", \"Asia/Khandyga\", \"Asia/Kolkata\", \"Asia/Krasnoyarsk\", \"Asia/Kuala_Lumpur\", \"Asia/Kuching\", \"Asia/Macau\", \"Asia/Magadan\", \"Asia/Makassar\", \"Asia/Manila\", \"Asia/Nicosia\", \"Asia/Novokuznetsk\", \"Asia/Novosibirsk\", \"Asia/Omsk\", \"Asia/Oral\", \"Asia/Pontianak\", \"Asia/Pyongyang\", \"Asia/Qatar\", \"Asia/Qostanay\", \"Asia/Qyzylorda\", \"Asia/Riyadh\", \"Asia/Sakhalin\", \"Asia/Samarkand\", \"Asia/Seoul\", \"Asia/Shanghai\", \"Asia/Singapore\", \"Asia/Srednekolymsk\", \"Asia/Taipei\", \"Asia/Tashkent\", \"Asia/Tbilisi\", \"Asia/Tehran\", \"Asia/Thimphu\", \"Asia/Tokyo\", \"Asia/Tomsk\", \"Asia/Ulaanbaatar\", \"Asia/Urumqi\", \"Asia/Ust-Nera\", \"Asia/Vladivostok\", \"Asia/Yakutsk\", \"Asia/Yangon\", \"Asia/Yekaterinburg\", \"Asia/Yerevan\", \"Atlantic/Azores\", \"Atlantic/Bermuda\", \"Atlantic/Canary\", \"Atlantic/Cape_Verde\", \"Atlantic/Faroe\", \"Atlantic/Madeira\", \"Atlantic/Reykjavik\", \"Atlantic/South_Georgia\", \"Atlantic/Stanley\", \"Australia/Adelaide\", \"Australia/Brisbane\", \"Australia/Broken_Hill\", \"Australia/Currie\", \"Australia/Darwin\", \"Australia/Eucla\", \"Australia/Hobart\", \"Australia/Lindeman\", \"Australia/Lord_Howe\", \"Australia/Melbourne\", \"Australia/Perth\", \"Australia/Sydney\", \"CET\", \"CST6CDT\", \"EET\", \"EST\", \"EST5EDT\", \"Etc/GMT\", \"Etc/GMT+1\", \"Etc/GMT+10\", \"Etc/GMT+11\", \"Etc/GMT+12\", \"Etc/GMT+2\", \"Etc/GMT+3\", \"Etc/GMT+4\", \"Etc/GMT+5\", \"Etc/GMT+6\", \"Etc/GMT+7\", \"Etc/GMT+8\", \"Etc/GMT+9\", \"Etc/GMT-1\", \"Etc/GMT-10\", \"Etc/GMT-11\", \"Etc/GMT-12\", \"Etc/GMT-13\", \"Etc/GMT-14\", \"Etc/GMT-2\", \"Etc/GMT-3\", \"Etc/GMT-4\", \"Etc/GMT-5\", \"Etc/GMT-6\", \"Etc/GMT-7\", \"Etc/GMT-8\", \"Etc/GMT-9\", \"Etc/UTC\", \"Europe/Amsterdam\", \"Europe/Andorra\", \"Europe/Astrakhan\", \"Europe/Athens\", \"Europe/Belgrade\", \"Europe/Berlin\", \"Europe/Brussels\", \"Europe/Bucharest\", \"Europe/Budapest\", \"Europe/Chisinau\", \"Europe/Copenhagen\", \"Europe/Dublin\", \"Europe/Gibraltar\", \"Europe/Helsinki\", \"Europe/Istanbul\", \"Europe/Kaliningrad\", \"Europe/Kiev\", \"Europe/Kirov\", \"Europe/Lisbon\", \"Europe/London\", \"Europe/Luxembourg\", \"Europe/Madrid\", \"Europe/Malta\", \"Europe/Minsk\", \"Europe/Monaco\", \"Europe/Moscow\", \"Europe/Oslo\", \"Europe/Paris\", \"Europe/Prague\", \"Europe/Riga\", \"Europe/Rome\", \"Europe/Samara\", \"Europe/Saratov\", \"Europe/Simferopol\", \"Europe/Sofia\", \"Europe/Stockholm\", \"Europe/Tallinn\", \"Europe/Tirane\", \"Europe/Ulyanovsk\", \"Europe/Uzhgorod\", \"Europe/Vienna\", \"Europe/Vilnius\", \"Europe/Volgograd\", \"Europe/Warsaw\", \"Europe/Zaporozhye\", \"Europe/Zurich\", \"HST\", \"Indian/Chagos\", \"Indian/Christmas\", \"Indian/Cocos\", \"Indian/Kerguelen\", \"Indian/Mahe\", \"Indian/Maldives\", \"Indian/Mauritius\", \"Indian/Reunion\", \"MET\", \"MST\", \"MST7MDT\", \"PST8PDT\", \"Pacific/Apia\", \"Pacific/Auckland\", \"Pacific/Bougainville\", \"Pacific/Chatham\", \"Pacific/Chuuk\", \"Pacific/Easter\", \"Pacific/Efate\", \"Pacific/Enderbury\", \"Pacific/Fakaofo\", \"Pacific/Fiji\", \"Pacific/Funafuti\", \"Pacific/Galapagos\", \"Pacific/Gambier\", \"Pacific/Guadalcanal\", \"Pacific/Guam\", \"Pacific/Honolulu\", \"Pacific/Kiritimati\", \"Pacific/Kosrae\", \"Pacific/Kwajalein\", \"Pacific/Majuro\", \"Pacific/Marquesas\", \"Pacific/Nauru\", \"Pacific/Niue\", \"Pacific/Norfolk\", \"Pacific/Noumea\", \"Pacific/Pago_Pago\", \"Pacific/Palau\", \"Pacific/Pitcairn\", \"Pacific/Pohnpei\", \"Pacific/Port_Moresby\", \"Pacific/Rarotonga\", \"Pacific/Tahiti\", \"Pacific/Tarawa\", \"Pacific/Tongatapu\", \"Pacific/Wake\", \"Pacific/Wallis\", \"WET\"}]\r\nin\r\n  #\"Local Time Zone\";\r\nshared #\"Last Refresh Local\" = let\r\n  Source = Json.Document(Web.Contents(\"http://worldtimeapi.org/api/timezone/\" & #\"Local Time Zone\")),\r\n  #\"Converted to Table\" = Record.ToTable(Source),\r\n  #\"Pivoted Column\" = Table.Pivot(#\"Converted to Table\", List.Distinct(#\"Converted to Table\"[Name]), \"Name\", \"Value\"),\r\n  #\"Removed Other Columns\" = Table.SelectColumns(#\"Pivoted Column\", {\"datetime\"}),\r\n  #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Removed Other Columns\", \"datetime\", Splitter.SplitTextByDelimiter(\".\", QuoteStyle.Csv), {\"Last Refresh\", \"datetime.2\"}),\r\n  #\"Changed Type\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\", {{\"Last Refresh\", type datetime}}),\r\n  #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\", {\"datetime.2\"}),\r\n  Navigation = #\"Removed Columns\"{0}[Last Refresh]\r\nin\r\n  Navigation;\r\nshared Date_Dim = let\r\n  #\"*PARAMETERS*\" = 1,\r\n  // This parameter determines the first year of this date dimension. Dates will begin on the 1st of January of the year written.\r\n  FromYear = Date.Year(#\"Dynamic Start Date\"),\r\n  // This parameter determines the last year of this date dimension. The final date of the table will be December 31st of the year written.\r\n  ToYear = Date.Year(#\"Dynamic End Date\"),\r\n  // Use this parameter to set the month number that is the start of your organization's fiscal/financial year. (Example: If your fiscal year starts July, 7 should be written here.)\r\n  StartofFiscalYear = #\"Fiscal Year Start Month\",\r\n  // This parameter determines the day considered the first day of the week.\r\n  firstDayofWeek = Day.Monday,\r\n  // Clear depiction of the first day of your table.\r\n  FromDate = #\"Start Date\",\r\n  // Clear depiction of the last day of your table.\r\n  ToDate = #\"Dynamic End Date\",\r\n  #\"*DATE TABLE*\" = 1,\r\n  Source = List.Dates(\r\n    FromDate,\r\n    Duration.Days(ToDate-FromDate)+1,\r\n    #duration(1,0,0,0)\r\n    ),\r\n  #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r\n  #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\", {{\"Column1\", \"Date\"}}),\r\n  #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Date\", type date}}),\r\n  #\"Inserted Year\" = Table.AddColumn(#\"Changed Type\", \"Year\", each Date.Year([Date]), Int64.Type),\r\n  #\"Inserted Start of Year\" = Table.AddColumn(#\"Inserted Year\", \"Start of Year\", each Date.StartOfYear([Date]), type date),\r\n  #\"Inserted End of Year\" = Table.AddColumn(#\"Inserted Start of Year\", \"End of Year\", each Date.EndOfYear([Date]), type date),\r\n  #\"Inserted Month\" = Table.AddColumn(#\"Inserted End of Year\", \"Month\", each Date.Month([Date]), Int64.Type),\r\n  #\"Inserted Start of Month\" = Table.AddColumn(#\"Inserted Month\", \"Start of Month\", each Date.StartOfMonth([Date]), type date),\r\n  #\"Inserted End of Month\" = Table.AddColumn(#\"Inserted Start of Month\", \"End of Month\", each Date.EndOfMonth([Date]), type date),\r\n  #\"Inserted Days in Month\" = Table.AddColumn(#\"Inserted End of Month\", \"Days in Month\", each Date.DaysInMonth([Date]), Int64.Type),\r\n  #\"Inserted Day\" = Table.AddColumn(#\"Inserted Days in Month\", \"Day\", each Date.Day([Date]), Int64.Type),\r\n  #\"Inserted Day Name\" = Table.AddColumn(#\"Inserted Day\", \"Day Name\", each Date.DayOfWeekName([Date]), type text),\r\n  #\"Inserted Day of Week\" = Table.AddColumn(#\"Inserted Day Name\", \"Day of Week\", each Date.DayOfWeek([Date]), Int64.Type),\r\n  #\"Inserted Day of Year\" = Table.AddColumn(#\"Inserted Day of Week\", \"Day of Year\", each Date.DayOfYear([Date]), Int64.Type),\r\n  #\"Inserted Month Name\" = Table.AddColumn(#\"Inserted Day of Year\", \"Month Name\", each Date.MonthName([Date]), type text),\r\n  #\"Inserted Quarter\" = Table.AddColumn(#\"Inserted Month Name\", \"Quarter\", each Date.QuarterOfYear([Date]), Int64.Type),\r\n  #\"Inserted Start of Quarter\" = Table.AddColumn(#\"Inserted Quarter\", \"Start of Quarter\", each Date.StartOfQuarter([Date]), type date),\r\n  #\"Inserted End of Quarter\" = Table.AddColumn(#\"Inserted Start of Quarter\", \"End of Quarter\", each Date.EndOfQuarter([Date]), type date),\r\n  #\"Inserted Week of Year\" = Table.AddColumn(#\"Inserted End of Quarter\", \"Week of Year\", each Date.WeekOfYear([Date],firstDayofWeek), Int64.Type),\r\n  #\"Inserted Week of Month\" = Table.AddColumn(#\"Inserted Week of Year\", \"Week of Month\", each Date.WeekOfMonth([Date],firstDayofWeek), Int64.Type),\r\n  #\"Inserted Start of Week\" = Table.AddColumn(#\"Inserted Week of Month\", \"Start of Week\", each Date.StartOfWeek([Date],firstDayofWeek), type date),\r\n  #\"Inserted End of Week\" = Table.AddColumn(#\"Inserted Start of Week\", \"End of Week\", each Date.EndOfWeek([Date],firstDayofWeek), type date),\r\n  FiscalMonthBaseIndex = 13 - StartofFiscalYear,\r\n  adjustedFiscalMonthBaseIndex = if(FiscalMonthBaseIndex>=12 or FiscalMonthBaseIndex<0) then 0 else FiscalMonthBaseIndex,\r\n  #\"Added Custom\" = Table.AddColumn(#\"Inserted End of Week\", \"FiscalBaseDate\", each Date.AddMonths([Date],adjustedFiscalMonthBaseIndex)),\r\n  #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\", {{\"FiscalBaseDate\", type date}}),\r\n  #\"Inserted Year1\" = Table.AddColumn(#\"Changed Type1\", \"Year.1\", each Date.Year([FiscalBaseDate]), Int64.Type),\r\n  #\"Renamed Columns1\" = Table.RenameColumns(#\"Inserted Year1\", {{\"Year.1\", \"Fiscal Year\"}}),\r\n  #\"Inserted Quarter1\" = Table.AddColumn(#\"Renamed Columns1\", \"Quarter.1\", each Date.QuarterOfYear([FiscalBaseDate]), Int64.Type),\r\n  #\"Renamed Columns2\" = Table.RenameColumns(#\"Inserted Quarter1\", {{\"Quarter.1\", \"Fiscal Quarter\"}}),\r\n  #\"Inserted Fiscal Month\" = Table.AddColumn(#\"Renamed Columns2\", \"Fiscal Month\", each Date.Month([FiscalBaseDate]), Int64.Type),\r\n  #\"Removed Columns\" = Table.RemoveColumns(#\"Inserted Fiscal Month\", {\"FiscalBaseDate\"}),\r\n  // Is Past is a useful filter when working with To Date formulas in Power BI, although there are certainly many other reasons to keep this filter in your backpocket.\r\n  #\"Is Past\" = Table.AddColumn(#\"Removed Columns\", \"Is Past\", each if [Date] < DateTime.Date(DateTime.LocalNow()) then true else false, type text),\r\n  // Below are labels to help users identify slicers/filters/categories more clearly.\r\n  #\"Quarter Name\" = Table.AddColumn(#\"Is Past\", \"Quarter Name\", each Text.Combine({\"Q\", Text.From([Quarter], \"en-US\")}), type text),\r\n  #\"Day Name Shortened\" = Table.AddColumn(#\"Quarter Name\", \"Day Name Shortened\", each Text.Start([Day Name], 3), type text),\r\n  #\"Month Name Shortened\" = Table.AddColumn(#\"Day Name Shortened\", \"Month Name Shortened\", each Text.Start([Month Name], 3), type text),\r\n  #\"Month Year\" = Table.AddColumn(#\"Month Name Shortened\", \"Month Year\", each Text.Combine({[Month Name Shortened], \" \", Text.From([Year], \"en-US\")}), type text),\r\n  #\"Quarter Year\" = Table.AddColumn(#\"Month Year\", \"Quarter Year\", each Text.Combine({[Quarter Name], \" \", Text.From([Year], \"en-US\")}), type text),\r\n  // Below are group indexes used to streamline some calculations.\r\n  #\"==Group Indexes==\" = #\"Quarter Year\",\r\n  #\"Grouped Rows\" = Table.Group(#\"Quarter Year\", {\"Year\", \"Month\"}, {{\"Month Year Index Grouping\", each _, type table [Date=date, Year=number, Start of Year=date, End of Year=date, Month=number, Start of Month=date, End of Month=date, Days in Month=number, Day=number, Day Name=text, Day of Week=number, Day of Year=number, Month Name=text, Quarter=number, Start of Quarter=date, End of Quarter=date, Week of Year=number, Week of Month=number, Start of Week=date, End of Week=date, Fiscal Year=number, Fiscal Quarter=number, Fiscal Month=number, Is Past=logical, Quarter Name=text, Day Name Shortened=text, Month Name Shortened=text, Month Year=text, Quarter Year=text]}}),\r\n  #\"Added Index\" = Table.AddIndexColumn(#\"Grouped Rows\", \"Month Year Index\", 1, 1),\r\n  #\"Expanded Month Year Index\" = Table.ExpandTableColumn(#\"Added Index\", \"Month Year Index Grouping\", {\"Date\", \"Start of Year\", \"End of Year\", \"Start of Month\", \"End of Month\", \"Days in Month\", \"Day\", \"Day Name\", \"Day of Week\", \"Day of Year\", \"Month Name\", \"Quarter\", \"Start of Quarter\", \"End of Quarter\", \"Week of Year\", \"Week of Month\", \"Start of Week\", \"End of Week\", \"Fiscal Year\", \"Fiscal Quarter\", \"Fiscal Month\", \"Is Past\", \"Quarter Name\", \"Day Name Shortened\", \"Month Name Shortened\", \"Month Year\", \"Quarter Year\"}, {\"Date\", \"Start of Year\", \"End of Year\", \"Start of Month\", \"End of Month\", \"Days in Month\", \"Day\", \"Day Name\", \"Day of Week\", \"Day of Year\", \"Month Name\", \"Quarter\", \"Start of Quarter\", \"End of Quarter\", \"Week of Year\", \"Week of Month\", \"Start of Week\", \"End of Week\", \"Fiscal Year\", \"Fiscal Quarter\", \"Fiscal Month\", \"Is Past\", \"Quarter Name\", \"Day Name Shortened\", \"Month Name Shortened\", \"Month Year\", \"Quarter Year\"}),\r\n  #\"Grouped Rows1\" = Table.Group(#\"Expanded Month Year Index\", {\"Year\", \"Quarter\"}, {{\"Quarter Year Index Grouping\", each _, type table [Date=date, Year=number, Start of Year=date, End of Year=date, Month=number, Start of Month=date, End of Month=date, Days in Month=number, Day=number, Day Name=text, Day of Week=number, Day of Year=number, Month Name=text, Quarter=number, Start of Quarter=date, End of Quarter=date, Week of Year=number, Week of Month=number, Start of Week=date, End of Week=date, Fiscal Year=number, Fiscal Quarter=number, Fiscal Month=number, Is Past=logical, Quarter Name=text, Day Name Shortened=text, Month Name Shortened=text, Month Year=text, Quarter Year=text, Month Year Index=number]}}),\r\n  #\"Added Index1\" = Table.AddIndexColumn(#\"Grouped Rows1\", \"Quarter Year Index\", 1, 1),\r\n  #\"Expanded Quarter Year Index Grouping\" = Table.ExpandTableColumn(#\"Added Index1\", \"Quarter Year Index Grouping\", {\"Date\", \"Start of Year\", \"End of Year\", \"Month\", \"Start of Month\", \"End of Month\", \"Days in Month\", \"Day\", \"Day Name\", \"Day of Week\", \"Day of Year\", \"Month Name\", \"Start of Quarter\", \"End of Quarter\", \"Week of Year\", \"Week of Month\", \"Start of Week\", \"End of Week\", \"Fiscal Year\", \"Fiscal Quarter\", \"Fiscal Month\", \"Is Past\", \"Quarter Name\", \"Day Name Shortened\", \"Month Name Shortened\", \"Month Year\", \"Quarter Year\", \"Month Year Index\"}, {\"Date\", \"Start of Year\", \"End of Year\", \"Month\", \"Start of Month\", \"End of Month\", \"Days in Month\", \"Day\", \"Day Name\", \"Day of Week\", \"Day of Year\", \"Month Name\", \"Start of Quarter\", \"End of Quarter\", \"Week of Year\", \"Week of Month\", \"Start of Week\", \"End of Week\", \"Fiscal Year\", \"Fiscal Quarter\", \"Fiscal Month\", \"Is Past\", \"Quarter Name\", \"Day Name Shortened\", \"Month Name Shortened\", \"Month Year\", \"Quarter Year\", \"Month Year Index\"}),\r\n  #\"Grouped Rows2\" = Table.Group(#\"Expanded Quarter Year Index Grouping\", {\"Year\", \"Week of Year\"}, {{\"Year Week Index Grouping\", each _, type table [Date=date, Year=number, Start of Year=date, End of Year=date, Month=number, Start of Month=date, End of Month=date, Days in Month=number, Day=number, Day Name=text, Day of Week=number, Day of Year=number, Month Name=text, Quarter=number, Start of Quarter=date, End of Quarter=date, Week of Year=number, Week of Month=number, Start of Week=date, End of Week=date, Fiscal Year=number, Fiscal Quarter=number, Fiscal Month=number, Is Past=logical, Quarter Name=text, Day Name Shortened=text, Month Name Shortened=text, Month Year=text, Quarter Year=text, Month Year Index=number, Quarter Year Index=number]}}),\r\n  #\"Added Index2\" = Table.AddIndexColumn(#\"Grouped Rows2\", \"Year Week Index\", 1, 1),\r\n  #\"Expanded Year Week Index Grouping\" = Table.ExpandTableColumn(#\"Added Index2\", \"Year Week Index Grouping\", {\"Date\", \"Start of Year\", \"End of Year\", \"Month\", \"Start of Month\", \"End of Month\", \"Days in Month\", \"Day\", \"Day Name\", \"Day of Week\", \"Day of Year\", \"Month Name\", \"Quarter\", \"Start of Quarter\", \"End of Quarter\", \"Week of Month\", \"Start of Week\", \"End of Week\", \"Fiscal Year\", \"Fiscal Quarter\", \"Fiscal Month\", \"Is Past\", \"Quarter Name\", \"Day Name Shortened\", \"Month Name Shortened\", \"Month Year\", \"Quarter Year\", \"Month Year Index\", \"Quarter Year Index\"}, {\"Date\", \"Start of Year\", \"End of Year\", \"Month\", \"Start of Month\", \"End of Month\", \"Days in Month\", \"Day\", \"Day Name\", \"Day of Week\", \"Day of Year\", \"Month Name\", \"Quarter\", \"Start of Quarter\", \"End of Quarter\", \"Week of Month\", \"Start of Week\", \"End of Week\", \"Fiscal Year\", \"Fiscal Quarter\", \"Fiscal Month\", \"Is Past\", \"Quarter Name\", \"Day Name Shortened\", \"Month Name Shortened\", \"Month Year\", \"Quarter Year\", \"Month Year Index\", \"Quarter Year Index\"}),\r\n  // Type is lost after grouping and expanding. Re-adding column types here.\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Expanded Year Week Index Grouping\", {{\"Date\", type date}, {\"Month\", Int64.Type}, {\"Fiscal Month\", Int64.Type}, {\"Year\", Int64.Type}, {\"Days in Month\", Int64.Type}, {\"Day\", Int64.Type}, {\"Day of Week\", Int64.Type}, {\"Day of Year\", Int64.Type}, {\"Quarter\", Int64.Type}, {\"Week of Year\", Int64.Type}, {\"Week of Month\", Int64.Type}, {\"Fiscal Year\", Int64.Type}, {\"Fiscal Quarter\", Int64.Type}, {\"Month Year Index\", Int64.Type}, {\"Quarter Year Index\", Int64.Type}, {\"Year Week Index\", Int64.Type}}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Changed column type 1\", {\"Date\", \"Year\", \"Week of Year\", \"Start of Year\", \"End of Year\", \"Month\", \"Start of Month\", \"End of Month\", \"Days in Month\", \"Day\", \"Day Name\", \"Day of Week\", \"Day of Year\", \"Month Name\", \"Quarter\", \"Start of Quarter\", \"End of Quarter\", \"Week of Month\", \"Start of Week\", \"End of Week\", \"Fiscal Year\", \"Fiscal Quarter\", \"Fiscal Month\", \"Is Past\", \"Quarter Name\", \"Day Name Shortened\", \"Month Name Shortened\", \"Month Year\", \"Quarter Year\", \"Month Year Index\", \"Quarter Year Index\", \"Year Week Index\"})\r\nin\r\n  #\"Reordered columns\";\r\nshared #\"Start Date\" = let\r\n  #\"Start Year\" = #date(2017, 1, 1) meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type date, List = {#date(2000, 1, 1), #date(2001, 1, 1), #date(2002, 1, 1), #date(2003, 1, 1), #date(2004, 1, 1), #date(2005, 1, 1), #date(2006, 1, 1), #date(2007, 1, 1), #date(2008, 1, 1), #date(2009, 1, 1), #date(2010, 1, 1), #date(2011, 1, 1), #date(2012, 1, 1), #date(2013, 1, 1), #date(2014, 1, 1), #date(2015, 1, 1), #date(2016, 1, 1), #date(2017, 1, 1), #date(2018, 1, 1), #date(2019, 1, 1), #date(2020, 1, 1), #date(2021, 1, 1), #date(2022, 1, 1), #date(2023, 1, 1), #date(2024, 1, 1), #date(2025, 1, 1), #date(2026, 1, 1), #date(2027, 1, 1), #date(2028, 1, 1), #date(2029, 1, 1), #date(2030, 1, 1)}, DefaultValue = 2020]\r\nin\r\n  #\"Start Year\";\r\nshared #\"End Date\" = let\r\n  #\"End Year\" = #date(2025, 12, 31) meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type date, List = {#date(2000, 12, 31), #date(2001, 12, 31), #date(2002, 12, 31), #date(2003, 12, 31), #date(2004, 12, 31), #date(2005, 12, 31), #date(2006, 12, 31), #date(2007, 12, 31), #date(2008, 12, 31), #date(2009, 12, 31), #date(2010, 12, 31), #date(2011, 12, 31), #date(2012, 12, 31), #date(2013, 12, 31), #date(2014, 12, 31), #date(2015, 12, 31), #date(2016, 12, 31), #date(2017, 12, 31), #date(2018, 12, 31), #date(2019, 12, 31), #date(2020, 12, 31), #date(2021, 12, 31), #date(2022, 12, 31), #date(2023, 12, 31), #date(2024, 12, 31), #date(2025, 12, 31), #date(2026, 12, 31), #date(2027, 12, 31), #date(2028, 12, 31), #date(2029, 12, 31), #date(2030, 12, 31)}, DefaultValue = #date(2025, 12, 31)]\r\nin\r\n  #\"End Year\";\r\nshared #\"Years Back\" = let\r\n  #\"Years Back\" = 0 meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type number, List = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, DefaultValue = 1]\r\nin\r\n  #\"Years Back\";\r\nshared #\"Years Forward\" = let\r\n  #\"Years Forward\" = 0 meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type number, List = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, DefaultValue = 5]\r\nin\r\n  #\"Years Forward\";\r\nshared #\"Fiscal Year Start Month\" = let\r\n  #\"Start of Fiscal Year Month\" = 7 meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type number, List = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, DefaultValue = 7]\r\nin\r\n  #\"Start of Fiscal Year Month\";\r\nshared #\"Dynamic Start Date\" = let\r\n  Source = #date(Date.Year(DateTimeZone.FixedUtcNow()) - #\"Years Back\",1,1)\r\nin\r\n  Source;\r\nshared #\"Dynamic End Date\" = let\r\n  Source = #date(Date.Year(DateTimeZone.FixedUtcNow()) + #\"Years Forward\",12,31)\r\nin\r\n  Source;\r\nshared TOPN = let\r\n  TOPN = 1000 meta [IsParameterQuery = true, IsParameterQueryRequired = false, Type = type number, List = {100, 1000, 10000, 100000, 1000000000000}, DefaultValue = 1000]\r\nin\r\n  TOPN;\r\nshared RangeStart = let\r\n  RangeStart1 = #datetime(1990, 1, 1, 0, 0, 0) meta [IsParameterQuery = true, IsParameterQueryRequired = false, Type = type datetime]\r\nin\r\n  RangeStart1;\r\nshared RangeEnd = let\r\n  RangeEnd1 = #datetime(2030, 12, 31, 0, 0, 0) meta [IsParameterQuery = true, IsParameterQueryRequired = false, Type = type datetime]\r\nin\r\n  RangeEnd1;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"02a394db-c514-4acd-829b-a0946840d68a\",\"name\":\"Time\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"16c59665-03d8-41d7-b6fe-3da6417449cf\",\"name\":\"Date\",\"description\":\"\",\"parentId\":null,\"order\":0},{\"id\":\"c1437975-acc3-420d-9534-0d1af5ee9e0e\",\"name\":\"Dev Help\",\"description\":\"\",\"parentId\":null,\"order\":1}]"}],"entities":[{"$type":"LocalEntity","name":"Time_Dim","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Time_Dim.csv"},"attributes":[{"name":"Time","dataType":"time"},{"name":"Start of Hour","dataType":"time"},{"name":"End of Hour","dataType":"time"},{"name":"Hour","dataType":"double"},{"name":"Minute","dataType":"double"},{"name":"Second","dataType":"double"},{"name":"AM/PM","dataType":"string"},{"name":"Hour Label","dataType":"string"},{"name":"Minute Label","dataType":"string"},{"name":"Second Label","dataType":"string"},{"name":"Hour Bin 12","dataType":"double"},{"name":"Hour Bin 8","dataType":"int64"},{"name":"Hour Bin 6","dataType":"int64"},{"name":"Hour Bin 4","dataType":"int64"},{"name":"Hour Bin 3","dataType":"int64"},{"name":"Hour Bin 2","dataType":"int64"},{"name":"Minute Bin 30","dataType":"double"},{"name":"Minute Bin 15","dataType":"double"},{"name":"Minute Bin 10","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2021-02-15T07:30:11.6997596+00:00","location":"https://wabiweuscdsap1.blob.core.windows.net:443/5a5dc463-d734-46a1-aa55-7e855d5084d9/Time_Dim.csv?snapshot=2021-02-15T07%3A30%3A11.6615387Z"}]},{"$type":"LocalEntity","name":"Refresh Info","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Refresh%20Info.csv"},"attributes":[{"name":"Last Refresh UTC","dataType":"dateTime"},{"name":"Last Refresh Local","dataType":"dateTime"},{"name":"Local Time Zone","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2021-02-15T07:30:06.5949919+00:00","location":"https://wabiweuscdsap1.blob.core.windows.net:443/5a5dc463-d734-46a1-aa55-7e855d5084d9/Refresh%20Info.csv?snapshot=2021-02-15T07%3A30%3A06.3837881Z"}]},{"$type":"LocalEntity","name":"Date_Dim","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Date_Dim.csv"},"attributes":[{"name":"Date","dataType":"date"},{"name":"Year","dataType":"int64"},{"name":"Week of Year","dataType":"int64"},{"name":"Start of Year","dataType":"date"},{"name":"End of Year","dataType":"date"},{"name":"Month","dataType":"int64"},{"name":"Start of Month","dataType":"date"},{"name":"End of Month","dataType":"date"},{"name":"Days in Month","dataType":"int64"},{"name":"Day","dataType":"int64"},{"name":"Day Name","dataType":"string"},{"name":"Day of Week","dataType":"int64"},{"name":"Day of Year","dataType":"int64"},{"name":"Month Name","dataType":"string"},{"name":"Quarter","dataType":"int64"},{"name":"Start of Quarter","dataType":"date"},{"name":"End of Quarter","dataType":"date"},{"name":"Week of Month","dataType":"int64"},{"name":"Start of Week","dataType":"date"},{"name":"End of Week","dataType":"date"},{"name":"Fiscal Year","dataType":"int64"},{"name":"Fiscal Quarter","dataType":"int64"},{"name":"Fiscal Month","dataType":"int64"},{"name":"Is Past","dataType":"boolean"},{"name":"Quarter Name","dataType":"string"},{"name":"Day Name Shortened","dataType":"string"},{"name":"Month Name Shortened","dataType":"string"},{"name":"Month Year","dataType":"string"},{"name":"Quarter Year","dataType":"string"},{"name":"Month Year Index","dataType":"int64"},{"name":"Quarter Year Index","dataType":"int64"},{"name":"Year Week Index","dataType":"int64"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2021-02-15T07:30:06.5299592+00:00","location":"https://wabiweuscdsap1.blob.core.windows.net:443/5a5dc463-d734-46a1-aa55-7e855d5084d9/Date_Dim.csv?snapshot=2021-02-15T07%3A30%3A06.4988701Z"}]}]}