let
  // This Time Dimension was sourced largely from the time dimensions freely provided by FourMoo and Radacad. Generous people are awesome people.
  Source = List.Times(#time(0, 0, 0), 84600, #duration(0, 0, 0, 1)),
  #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
  #"Renamed Columns" = Table.RenameColumns(#"Converted to Table", {{"Column1", "Time"}}),
  #"Changed column type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Time", type time}}),
  #"Start of Hour" = Table.AddColumn(#"Changed column type", "Start of Hour", each Time.StartOfHour([Time]), type time),
  #"End of Hour" = Table.AddColumn(#"Start of Hour", "End of Hour", each Time.EndOfHour([Time]), type time),
  Hour = Table.AddColumn(#"End of Hour", "Hour", each Time.Hour([Time]), type number),
  Minute = Table.AddColumn(Hour, "Minute", each Time.Minute([Time]), type number),
  Second = Table.AddColumn(Minute, "Second", each Time.Second([Time]), type number),
  #"AM/PM" = Table.AddColumn(Second, "AM/PM", each if [Hour] <= 11 then "AM" else "PM", type text),
  #"Hour Label" = Table.AddColumn(#"AM/PM", "Hour Label", each "0" & Text.From([Hour], "en-NZ"), type text),
  #"Extracted Last Characters" = Table.TransformColumns(#"Hour Label", {{"Hour Label", each Text.End(_, 2), type text}}),
  #"Minute Label" = Table.AddColumn(#"Extracted Last Characters", "Minute Label", each "0" & Text.From([Minute], "en-NZ"), type text),
  #"Extracted Last Characters1" = Table.TransformColumns(#"Minute Label", {{"Minute Label", each Text.End(_, 2), type text}}),
  #"Inserted Prefix2" = Table.AddColumn(#"Extracted Last Characters1", "Second Label", each "0" & Text.From([Second], "en-NZ"), type text),
  #"Extracted Last Characters2" = Table.TransformColumns(#"Inserted Prefix2", {{"Second Label", each Text.End(_, 2), type text}}),
  #"Hour Bin 12" = Table.AddColumn(#"Extracted Last Characters2", "Hour Bin 12", each Number.Mod([Hour], 12), type number),
  #"Hour Bin 8" = Table.AddColumn(#"Hour Bin 12", "Hour Bin 8", each Number.IntegerDivide([Hour], 8), Int64.Type),
  #"Hour Bin 6" = Table.AddColumn(#"Hour Bin 8", "Hour Bin 6", each Number.IntegerDivide([Hour], 6), Int64.Type),
  #"Hour Bin 4" = Table.AddColumn(#"Hour Bin 6", "Hour Bin 4", each Number.IntegerDivide([Hour], 4), Int64.Type),
  #"Hour Bin 3" = Table.AddColumn(#"Hour Bin 4", "Hour Bin 3", each Number.IntegerDivide([Hour], 3), Int64.Type),
  #"Hour Bin 2" = Table.AddColumn(#"Hour Bin 3", "Hour Bin 2", each Number.IntegerDivide([Hour], 2), Int64.Type),
  #"Minute Bin 30" = Table.AddColumn(#"Hour Bin 2", "Minute Bin 30", each Number.IntegerDivide([Minute], 30), Int64.Type),
  #"Multiplied Column" = Table.TransformColumns(#"Minute Bin 30", {{"Minute Bin 30", each _ * 30, type number}}),
  #"Minute Bin 15" = Table.AddColumn(#"Multiplied Column", "Minute Bin 15", each Number.IntegerDivide([Minute], 15), Int64.Type),
  #"Multiplied Column1" = Table.TransformColumns(#"Minute Bin 15", {{"Minute Bin 15", each _ * 15, type number}}),
  #"Minute Bin 10" = Table.AddColumn(#"Multiplied Column1", "Minute Bin 10", each Number.IntegerDivide([Minute], 10), Int64.Type),
  #"Multiplied Column2" = Table.TransformColumns(#"Minute Bin 10", {{"Minute Bin 10", each _ * 10, type number}})
in
  #"Multiplied Column2"
